@startuml

title __UTILS's Class Diagram__\n

  namespace com.journear.app {
    namespace core {
      namespace utils {
        class com.journear.app.core.utils.AppConstants {
            {static} + BASE_URL : String
            {static} + TIMEZONE : String
            {static} ~ EncryptionPassword : String
        }
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      namespace utils {
        class com.journear.app.core.utils.Encryptor {
            {static} - _key : SecretKey
            {static} + decryptMsg()
            {static} + encryptMsg()
            {static} - generateKey()
        }
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      namespace utils {
        class com.journear.app.core.utils.JnGeocoder {
            {static} ~ _GeoCodeItemsByRegion : Map<String, ArrayList<JnGeocodeItem>>
            {static} ~ lastAccessedRegion : String
            {static} + DownloadAndStoreGeocodingDataForRegion()
            {static} + GetGeocodingListForRegion()
            {static} + getGeoCodeItemsByRegion()
            {static} + getJnGeocodeItemById()
            {static} + getJnGeocodeItemById()
            {static} - readGeocodingDataCsv()
            {static} - readGeocodingDataCsv()
        }
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      namespace utils {
        class com.journear.app.core.utils.SerializerHelper {
            {static} ~ _conf : FSTConfiguration
            {static} + copyObject()
            {static} + deserialize()
            {static} + serialize()
            {static} - getFstConfiguration()
        }
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      namespace utils {
        class com.journear.app.core.utils.Validations {
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
