@startuml

title __CORE's Class Diagram__\n

  namespace com.journear.app {
    namespace core {
      class com.journear.app.core.IsValid {
          {static} + VALID_MOBILE_REGEX : String
          {static} + VALID_PASSWORD_REGEX : String
          {static} + VALID_USERNAME_REGEX : String
          {static} ~ DATE_FORMAT : String
          {static} + DoB()
          {static} + Mobile()
          {static} + email()
          {static} + password()
          {static} + userName()
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      class com.journear.app.core.LocalFunctions {
          {static} + getCurrentLoggedInUser()
          {static} + getCurrentRegisteredUser()
          {static} + launchMapActivityWithRoute()
          {static} + setCurrentJourney()
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      class com.journear.app.core.PeerFunctions {
          {static} + getNearbyDevices()
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      class com.journear.app.core.PersistentStore {
          {static} ~ singleton : PersistentStore
          {static} - creatingContext : Context
          - gson : Gson
          + getGson()
          {static} + getInstance()
          + getItem()
          + setItem()
          + setItem()
          - getSqliteDbHelper()
      }
    }
  }
  

  namespace com.journear.app {
    namespace core {
      class com.journear.app.core.ServerFunctions {
          + volleyQueue : RequestQueue
          ~ loginUrl : String
          ~ registerUrl : String
          {static} ~ singleton : ServerFunctions
          - LOGIN : String
          - REGISTER : String
          - USERNAME : String
          + authenticate()
          {static} + getInstance()
          + registerUser()
          - ServerFunctions()
      }
    }
  }
  

  com.journear.app.core.PersistentStore o-- com.journear.app.core.db.SqliteDbHelper : sqliteDbHelper



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
